### ISSUE TITLE
Output details and the downstream analysis

### ISSUE THREAD

**Issue by camelest** [seqscope/ficture#16]
Hi, thank you again for the great tool. I'm sorry for adding some naive questions.

- I assume each factor represents each cell type and the pseudo-bulk counts for each cell type are stored in
`nF12.d_12.decode.prj_12.r_4_5.posterior.count.tsv.gz`
Is there anyway that we could perform differential expression analysis using the output from `FICTURE`?
 
- To visualize or perform further analysis on the results by other downstream analysis tools such as `Seurat`,
how could we transfer the results from `FICTURE`? Is it acceptable to use `K1` from `nF12.d_12.decode.prj_12.r_4_5.pixel.sorted.tsv.gz` to assign the clustering results to each pixel?

Thank you so much for your help in advance.

**Comment by Yichen-Si** [comment]
1 As performing DE analysis between factors after pixel level assignment is subject to huge inflation due to double-dipping, I do not recommend doing so. But if you just want to do it for exploratory purposes you could use any pseudobulk analysis using the posterior count. 

2 Yes it is in general acceptable to use K1 as a categorical assignment. In the file you would also find the probabilities associated with each of the three top factors that provides a (very loose) assessment of the uncertainty.

**Comment by camelest** [comment]
@Yichen-Si Thank you so much for your prompt response.
I also checked #7 and successfully used `spatula` to obtain pixel-level `K1` assignment.

Now when I visualize the spatial distribution of each factor, the resulting clusters seem to have less distinct spatial distribution compared with cell segmented datasets. Do you have some advice on how to tune the parameters?

I'm working on Stereo-seq adult brain dataset. For example, I don't see clusters corresponding to hippocampus CA regions or some clusters span across cortex and thalamus even though the marker genes are mainly thalamus-specific.

I used `--n-factor` of of 12, 18, 24, 30 with `--train-width` of 12.

Thank you once again for your kind help.
