### ISSUE TITLE
Prior knowledge and parameter tuning

### ISSUE THREAD

**Issue by pakiessling** [seqscope/ficture#5]
Hi,

I am trying out ficture on our data.
Right now I can already say that it is incredibly fast and memory frugal - impressive!

I am curious about the inclusion of prior knowledge. In the preprint you write:

> Alternatively, the factors can also be obtained from external sc- and sn-RNA-seq references datasets, or from other spatially agnostic methods such as Seurat[16](https://www.biorxiv.org/content/10.1101/2023.11.04.565621v2.full#ref-16) and Scanpy[24](https://www.biorxiv.org/content/10.1101/2023.11.04.565621v2.full#ref-24) that learn factors based on grids. FICTURE can use these external factors as priors to initialize the LDA factors or use them directly as input factors

Is this implemented / documented yet?

I was also curious which of the parameters I would need to optimize for my **dense Merfish muscle sample**.
E.g.
```

nFactor=12 # Number of factors
sliding_step=2
train_nEpoch=3
train_width=12 # \sqrt{3} x the side length of the hexagon (um)
R=10 # We use R random initializations and pick one to fit the full model
fit_width=12 # Often equal or smaller than train_width (um)
anchor_res=4 # Distance between adjacent anchor points (um)
```

Do I need to change these values? I guess nFactor should correspond the number of major cell types I expect?
How do I select the other values and do I need to change them for different samples?

Ty!

**Comment by hyunminkang** [comment]
Hi @pakiessling - Sorry for the late response. I believe that @Yichen-Si was not notified of this issue due to technical hiccup.
 
We do have examples of using Seurat instead of LDA before the projection. 

Basically, what you need to do is to create your own model matrix from the Seurat output. An example is provided in the NovaScope downstream analysis example at https://seqscope.github.io/NovaScope-exemplary-downstream-analysis/analysis/hex_idx/step2b-seurat/ 

@WQ-CHENG may be able to answer questions on the example. Scanpy conversion can be done in a similar manner.
