### ISSUE TITLE
transcript-level output

### ISSUE THREAD

**Issue by ruqianl** [seqscope/ficture#7]
Great work! I really like the simulation module too.

I am wondering with FICTURE, is there any way to output the transcript-level results instead of pixel-level?

Transcript-level results for each transcript in the input `transcripts.tsv`

Thanks,
RL

**Comment by hyunminkang** [comment]
Hi @ruqianl -- sorry for the delayed response. I believe that @Yichen-Si can give a better answer to this, but this is what I can answer:

With the current version, the pixel-level output (.pixel.sorted.tsv.gz) should have a resolution high enough to associate it with individual transcripts. So you can "join" the transcript-level output with the pixel-level output using simple nearest neighbor search.

We have a plan to provide such a script to "join" the two datasets in the near future, but it has not been implemented into the package yet. We will update in this thread when this is done.

**Comment by hyunminkang** [comment]
Hi @ruqianl -- this is a bit of late follow-up, but we have published a tool to combine the transcript-level output and pixel-level output so that it can be effectively "joined" together.

Please see the example usage in the `spatula` documentation at the following URL:

https://seqscope.github.io/spatula/tools/join_pixel_tsv/

We will appreciate if you could let us know whether it worked for your own dataset or not.
